[build]
  publish = "_site"  # Your publish directory
  command = "npm run build"  # Your build command

[context.production.environment]
  GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no"
  PYTHON_VERSION = "3.8"